### ISSUE TITLE
Is the gem named dss_parser or dss-parser?

### ISSUE THREAD

**Issue by daveobriencouk** [stylefoundry/dss-parser#3]
I tried installing using the command stated on the readme:

    gem install dss-parser

And received this error:

    ERROR:  Could not find a valid gem 'dss-parser' (>= 0) in any repository
    ERROR:  Possible alternatives: dss_parser

So I tried:

    gem install dss_parser

Is that correct? If so the readme needs updating.

Thanks matey.

**Comment by bitscraps** [comment]
Thanks,  you are right the gem is called dos_parser and not css-parser.  The README has been updated.
